language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
- npm install node-gyp -g
- npm cache verify
- rm -rf node_modules
- npm install
sudo: enabled
dist: trusty
notifications:
  webhooks:
    urls:
      - https://arrowdiscord.com/travis-ci.php
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always