language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
- npm install node-gyp -g
- npm cache verify
- rm -rf node_modules
- npm install
sudo: enabled
dist: trusty
notifications:
  webhooks: https://arrowdiscord.com/travis-ci.php